minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@trickfilm400/rollup-plugin-off-main-thread@3.0.0-pre1'
  - semver@6.3.1
  - undici-types@6.21.0

shamefullyHoist: true
shellEmulator: true

overrides:
  typescript: ^6.0.3

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
