minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@kikiutils/mongoose' # TODO: remove it
  - '@kikiutils/shared' # TODO: remove it

trustPolicy: no-downgrade
trustPolicyExclude:
  # cssnano and postcss related
  # TODO: remove
  - cssnano@9.3.2
  - cssnano-preset-default@9.3.2
  - cssnano-utils@8.2.0
  - postcss-colormin@9.0.6
  - postcss-convert-values@9.0.7
  - postcss-discard-comments@9.0.6
  - postcss-discard-duplicates@9.0.5
  - postcss-discard-empty@9.0.6
  - postcss-discard-overridden@9.0.5
  - postcss-merge-longhand@9.2.1
  - postcss-merge-rules@9.1.2
  - postcss-minify-font-values@9.0.7
  - postcss-minify-gradients@9.0.6
  - postcss-minify-params@9.0.6
  - postcss-minify-selectors@9.0.6
  - postcss-normalize-charset@9.0.5
  - postcss-normalize-display-values@9.0.5
  - postcss-normalize-positions@9.0.6
  - postcss-normalize-repeat-style@9.0.5
  - postcss-normalize-string@9.0.5
  - postcss-normalize-timing-functions@9.0.5
  - postcss-normalize-unicode@9.0.5
  - postcss-normalize-url@9.0.5
  - postcss-normalize-whitespace@9.0.5
  - postcss-ordered-values@9.0.7
  - postcss-reduce-initial@9.0.6
  - postcss-reduce-transforms@9.0.4
  - postcss-svgo@9.0.4
  - postcss-unique-selectors@9.0.5
  - stylehacks@9.0.7

  - semver@6.3.1
  - undici-types@6.21.0

shamefullyHoist: true
shellEmulator: true

overrides:
  '@typescript-eslint/eslint-plugin': 8.71.0
  '@vue/language-core': 3.3.11
  typescript: ^6.0.3
  vue-tsc: 3.3.11

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
