minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - undici-types@6.21.0

shamefullyHoist: true
shellEmulator: true

overrides:
  '@vue/language-core': 3.3.11
  typescript: ^6.0.3
  vue-tsc: 3.3.11

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
